language: node_js
node_js:
- 6.0.0
branches:
  only:
  - source

cache:
  yarn: true
  directories:
    - node_modules

install: yarn install

before_script:
- git config --global user.name "roblovelett"
- git config --global user.email "rlovelett@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build